// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACNCi5AwSr-xO3xs3MHwBQQ0lkhnhoWiA',
    appId: '1:1035273527238:web:bb17b8316ec5cf1c439cc7',
    messagingSenderId: '1035273527238',
    projectId: 'mars-mind',
    authDomain: 'mars-mind.firebaseapp.com',
    storageBucket: 'mars-mind.firebasestorage.app',
    measurementId: 'G-T8Y3D1G6D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcuUBuau6oIBmqXZRYtqhHCDMN-FNjlwI',
    appId: '1:1035273527238:android:d97dbde25215c913439cc7',
    messagingSenderId: '1035273527238',
    projectId: 'mars-mind',
    storageBucket: 'mars-mind.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBox1NkB2kroST7Ml1kcVyGQ1MkKDEfDXs',
    appId: '1:1035273527238:ios:068b0eed36e9d027439cc7',
    messagingSenderId: '1035273527238',
    projectId: 'mars-mind',
    storageBucket: 'mars-mind.firebasestorage.app',
    iosClientId: '1035273527238-66b3o3ctuc9hj573nr6asc79nalno2g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.marsMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBox1NkB2kroST7Ml1kcVyGQ1MkKDEfDXs',
    appId: '1:1035273527238:ios:068b0eed36e9d027439cc7',
    messagingSenderId: '1035273527238',
    projectId: 'mars-mind',
    storageBucket: 'mars-mind.firebasestorage.app',
    iosClientId: '1035273527238-66b3o3ctuc9hj573nr6asc79nalno2g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.marsMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACNCi5AwSr-xO3xs3MHwBQQ0lkhnhoWiA',
    appId: '1:1035273527238:web:1a25e944b168665e439cc7',
    messagingSenderId: '1035273527238',
    projectId: 'mars-mind',
    authDomain: 'mars-mind.firebaseapp.com',
    storageBucket: 'mars-mind.firebasestorage.app',
    measurementId: 'G-QYT5HSTDLJ',
  );

}